[workspace]
members = [
    "crates/nwc-mobile",
    "crates/nwc-mobile-bolt11",
    "crates/nwc-mobile-http",
    "crates/nwc-mobile-nostr",
    "crates/nwc-mobile-tokio",
    "crates/nwc-mobile-uniffi",
    "tools/uniffi-bindgen",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.90"
repository = "https://github.com/ntheile/nwc-mobile"
license = "MIT"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
