// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-nwc-mobile.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NwcMobileSpec.h"

@interface NwcMobile : NSObject <NativeNwcMobileSpec>
#else
#import <React/RCTBridgeModule.h>

@interface NwcMobile : NSObject <RCTBridgeModule>
#endif

@end
