[package]
name = "nwc-mobile-bolt11"
description = "BOLT11 invoice integration for nwc-mobile wallet adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
lightning-invoice = { version = "=0.34.1", features = ["std"] }
nwc-mobile = { version = "=0.1.0", path = "../nwc-mobile" }

[dev-dependencies]
bitcoin = "=0.32.102"
lightning-types = "=0.3.5"

[lints]
workspace = true
