// Generated by uniffi-bindgen-react-native
#include "react-native-nwc-mobile.h"
#include "generated/nwc_mobile_uniffi.hpp"

namespace nwcmobile {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeNwcMobileUniffi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}